#!/usr/bin/env python3
"""Render and validate canonical LaTeX research macros from the projection map."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[1]
MAP_PATH = ROOT / "project/document_projection_map.json"
MAP_SCHEMA_PATH = ROOT / "schemas/document-projection-map.schema.json"
GRAPH_PATH = ROOT / "project/research_graph.json"
MACRO_RE = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")
FORBIDDEN_LATEX = ("\\write18", "\\openout", "\\input", "\\include", "\\end{document}")


def load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def render(projection: dict[str, Any]) -> str:
    lines = [
        "% Generated by tools/render_documents.py from project/document_projection_map.json.",
        "% Do not edit directly; update the structured projection map and rerun the renderer.",
        "",
    ]
    for name in sorted(projection["macros"]):
        if not MACRO_RE.fullmatch(name):
            raise ValueError(f"invalid macro name: {name}")
        text = " ".join(projection["macros"][name]["text"].split())
        lowered = text.lower()
        for token in FORBIDDEN_LATEX:
            if token.lower() in lowered:
                raise ValueError(f"forbidden LaTeX token in {name}: {token}")
        lines.append(f"\\newcommand{{\\{name}}}{{{text}}}")
    lines.append("")
    return "\n".join(lines)


def validate_projection(projection: dict[str, Any], graph: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    schema = load(MAP_SCHEMA_PATH)
    for error in Draft202012Validator(schema).iter_errors(projection):
        errors.append(f"projection_schema:{error.json_path}:{error.message}")

    entity_ids = {entity["id"] for entity in graph.get("entities", [])}
    for macro_name, macro in projection.get("macros", {}).items():
        for entity_id in macro.get("source_entity_ids", []):
            if entity_id not in entity_ids:
                errors.append(f"macro_source_missing:{macro_name}:{entity_id}")

    macro_names = set(projection.get("macros", {}))
    expected_documents = {"PREPROJECT", "ARTICLE", "DISSERTATION", "DOCTORAL_AGENDA"}
    actual_documents = set(projection.get("documents", {}))
    if actual_documents != expected_documents:
        errors.append("document_inventory_mismatch")

    for document_name, document in projection.get("documents", {}).items():
        path = ROOT / document["path"]
        if not path.is_file():
            errors.append(f"document_missing:{document_name}:{document['path']}")
            continue
        content = path.read_text(encoding="utf-8")
        for macro_name in document["required_macros"]:
            if macro_name not in macro_names:
                errors.append(f"required_macro_undefined:{document_name}:{macro_name}")
            if f"\\{macro_name}" not in content:
                errors.append(f"required_macro_unused:{document_name}:{macro_name}")

    required_invariants = {
        "QUESTION_CONSISTENT",
        "HYPOTHESIS_CONSISTENT",
        "METHOD_CONSISTENT",
        "EVIDENCE_STATUS_CONSISTENT",
        "LIMITATIONS_PROPAGATED",
        "DOCTORAL_AGENDA_NOT_THESIS",
        "NO_UNSUPPORTED_CLAIMS",
        "NO_FROZEN_PLACEHOLDERS",
    }
    if set(projection.get("invariants", [])) != required_invariants:
        errors.append("projection_invariants_incomplete")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if the committed generated file is stale.")
    args = parser.parse_args()

    projection = load(MAP_PATH)
    graph = load(GRAPH_PATH)
    errors = validate_projection(projection, graph)
    try:
        candidate = render(projection)
    except Exception as exc:
        errors.append(f"render:{exc}")
        candidate = ""

    generated_path = ROOT / projection["generated_file"]
    if args.check:
        if not generated_path.is_file():
            errors.append(f"generated_file_missing:{projection['generated_file']}")
        elif generated_path.read_text(encoding="utf-8") != candidate:
            errors.append("generated_file_stale")
    elif not errors:
        generated_path.parent.mkdir(parents=True, exist_ok=True)
        generated_path.write_text(candidate, encoding="utf-8")

    report = {
        "status": "PASS" if not errors else "FAIL",
        "mode": "CHECK" if args.check else "RENDER",
        "macro_count": len(projection.get("macros", {})),
        "document_count": len(projection.get("documents", {})),
        "errors": errors,
    }
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
